[default]
description = "Default permissions for the plugin"
permissions = [
  # User
  "allow-auth-login",
  "allow-get-users",
  "allow-get-user",
  "allow-remove-user",
  "allow-get-default-user",
  "allow-set-default-user",

  # Cluster
  "allow-create-cluster",
  "allow-remove-cluster",
  "allow-get-cluster",
  "allow-get-clusters",
  "allow-run-cluster",

  # Processor
  "allow-get-running-clusters",
  "allow-get-processes-by-path",
  "allow-kill-process",

  # Settings
  "allow-get-settings",
  "allow-set-settings",

  # Metadata
  "allow-get-minecraft-versions",

  # Package
  "allow-random-mods",
  "allow-get-mod",
  "allow-download-mod",

  # Other
  "allow-get-program-info",
  "allow-reload-webview",
  "allow-set-menu-bar-item-state",

  # Updater
  "allow-check-for-update",
  "allow-install-update",
]
